version: '3.3'
services:
    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
