version: '3.3'
services:
    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '54321:5432'
        volumes:
            - db:/var/lib/postgresql/data
    centrifugo:
        container_name: centrifugo
        image: centrifugo/centrifugo:v4-amd64
        volumes:
            - ./config.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - 8003:8000
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
volumes:
    db:
        driver: local
